version: '3'

services:
    website:
        build: ./website
        environment: 
            -   WORDPRESS_URL=${WORDPRESS_URL}
            -   BASE_IMAGE_URL=${BASE_IMAGE_URL}
        expose:
            - '3000'
        ports:
            - '3001:3000'
