version: '3'

services:
    db-headless:
        container_name: db-headless
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD="yes"
            - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
            - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - MYSQL_USER=${WORDPRESS_DB_USER}
        volumes: 
            - mysqlvolume:/var/lib/mysql
        image: mariadb
        ports:
            - '3307:3306'
    wp-headless:
        build: .
        command: bash -c 'install_wordpress && apache2-foreground'
        container_name: wp-headless
        image: syahrul12345/wp-headless
        depends_on:
            - db-headless
        env_file: ./.env
        ports:
            - '8080:8080'
        user: www-data
    website:
        build: ./website
        image: syahrul12345/website
        environment: 
            -   WORDPRESS_URL=${WORDPRESS_URL}
            -   BASE_IMAGE_URL=${BASE_IMAGE_URL}
        expose:
            - '3000'
        ports:
            - '3000:3000'
        links:
            - wp-headless
        labels:
            kompose.service.type: nodeport
            kompose.service.nodeport.expose: '3000'

        
    # website:
    #     command: bash -c 'yarn && yarn start'
    #     container_name: website
    #     environment:
    #         -   WORDPRESS_URL=${WORDPRESS_URL}
    #     expose:
    #         - '3000'
    #     image: node
    #     ports:
    #         - '3000:3000'
    #     user: node
    #     volumes:
    #         - ./website:/home/node/app
    #     working_dir: /home/node/app
    #     links: 
    #         - wp-headless
volumes: 
    mysqlvolume:
    wordpressvolume:
